config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :admins, controllers: { registrations: "registrations"}
  resources :houses
  resources :photos
  get '/message', to: 'messages#new'
  post '/message', to: 'messages#create'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :fullname, presence: true, length: { maximum: 50 }
  has_many :houses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :admin
  has_many :photos
  validates :name, presence: true, length: { maximum: 15 }
  validates :summary, presence: true, length: { maximum: 1000 }
  validates :address, presence: true
  validates :bedroom, numericality: true
  validates :bathroom, presence: true
  validates :garage, numericality: true
  validates :sf, numericality: { greater_than: 1500 }
  validates :price, numericality: { greater_than: 700000 }
  validates :lot_name, presence: true
  validates :no_ac_sf, numericality: true
end

app/models/message.rb
class Message < ApplicationRecord
  attr_accessor :name, :phone, :content

  validates :name, presence: true
  validates :phone, numericality: true, length: { minimum: 10, maximum: 15}
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :house
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :image, attachment_presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_houses

  private
  def set_houses
    @houses = House.all
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname])
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update]
  before_action :authenticate_admin!, except: [:show]

  def index
    @houses = current_admin.houses
  end

  def show
    @message = Message.new
    @photos = @house.photos
  end

  def new
    @house = current_admin.houses.build
  end

  def create
    @house = current_admin.houses.build(house_params)
    if @house.save

      if params[:images]
        params[:images].each do |image|
          @house.photos.create(image: image)
        end
      end

      @photos = @house.photos
      redirect_to @house, notice: "You successfully listed your house"
    else
      flash[:alert] = "All fields required!"
      render :new
    end
  end

  def edit
    if current_admin.id == @house.admin.id
      @photos = @house.photos
    else
      redirect_to root_path, notice: "You are not authorized!!!"
    end
  end

  def update
    if @house.update(house_params)

      if params[:images]
        params[:images].each do |image|
          @house.photos.create(image: image)
        end
      end

      redirect_to @house, notice: "Updated successfully"
    else
      flash[:alert] = "All fields required"
      render :edit
    end
  end

  def destroy
  end

  private
    def set_house
      @house = House.find(params[:id])
    end

    def house_params
      params.require(:house).permit(:name, :summary, :address, :bedroom, :bathroom, :garage, :sf, :price, :lot_name, :no_ac_sf)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.valid?
      MessageMailer.message_now(@message).deliver_now
      flash[:notice] = "Thanks #{@message.name}."
      redirect_to root_path
    else
      flash.now[:alert] = "All fields required!"
      render :new
    end
  end

  private

    def message_params
      params.require(:message).permit(:name, :phone, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @message = Message.new
    @houses = House.limit(6)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
  	@photo = Photo.find(params[:id])
  	house = @photo.house

  	@photo.destroy
  	@photos = Photo.where(house_id: house.id)

  	respond_to :js
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_admin_registered?, only: [:new, :create]

  protected

  def one_admin_registered?
    if ((Admin.count == 1) & (admin_signed_in?))
      redirect_to root_path
    elsif Admin.count == 1
      redirect_to root_path, notice: "You are not authorized to sign up!"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper

  def price_conver(price)
    str_pr = price.to_s

    if str_pr.length == 6
      "$ #{str_pr[0..2]},#{str_pr[3..5]}"
    elsif str_pr.length == 7
      "$ #{str_pr[0]},#{str_pr[1..3]},#{str_pr[4..6]}"
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/houses/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
  <!-- Indicators -->
  <% if @photos %>
      <ol class="carousel-indicators">
          <% @photos.each do |photo| %>
              <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
          <% end %>
      </ol>
  <% end %>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
      <% if @photos %>
          <% @photos.each do |photo| %>
              <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= link_to image_path(photo.image.url), class: "swipebox" do %>
                      <%= image_tag photo.image.url()%>
                  <% end %>
              </div>
           <% end %>
      <% end %>
  </div>
  <!-- Left and right controls -->
  <!-- <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
  </a> -->
</div>

app/views/houses/_form.html.erb
<section class="house-create-section">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <h2>Enter House Information Here</h2>

                        <%= form_for @house, html: { multipart: true } do |f| %>
                            <div class="form-group">
                                <%= f.text_field :name, autofocus: true, placeholder: "House name", class: "form-control" %>
                            </div>
                            <div class="form-group">
                                <%= f.text_area :summary, rows: 3,  placeholder: "Describe your house in few words", class: "form-control" %>
                            </div>
                            <div class="row">
                                <div class="col-md-8 col-sm-8">
                                    <div class="form-group">
                                        <%= f.text_field :address,  placeholder: "Address: 123 Street name, City, State Zipcode", class: "form-control" %>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-4">
                                    <div class="form-group">
                                        <%= f.text_field :lot_name,  placeholder: "Lot Number", class: "form-control" %>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <%= f.text_field :bedroom,  placeholder: "How many bedrooms?", class: "form-control" %>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <%= f.text_field :bathroom,  placeholder: "How many bathrooms?", class: "form-control" %>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <%= f.text_field :garage,  placeholder: "How many car garage?", class: "form-control" %>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <%= f.text_field :no_ac_sf,  placeholder: "Unconditioned area square footage?", class: "form-control" %>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <%= f.text_field :sf,  placeholder: "Conditioned area square footage", class: "form-control" %>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-addon">$</div>
                                            <%= f.text_field :price,  placeholder: "What is the price?", class: "form-control", id: "exampleInputAmount" %>
                                            <div class="input-group-addon">.00</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-upload btn btn-info pull-left">
                                        <span><i class="fa fa-camera" aria-hidden="true"></i></span>
                                        <%= file_field_tag "images[]", type: :file, multiple: true, class: "upload-btn" %>
                                    </div>
                                </div>
                            </div>
                            <div class="photos-render">
                                <%= render 'photos/list' %>
                            </div>
                            <div class="actions">
                                <%= f.submit "Publish", class: "hero-btn" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/houses/_google_maps.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-sm-8 col-xs-12">
            <div id="map"></div>
            <script src="https://maps.googleapis.com/maps/api/js"></script>
		    <script>
    		      function initialize() {
    		        var mapCanvas = document.getElementById('map');
    		        var mapOptions = {
    		          center: new google.maps.LatLng(<%= @house.latitude %>, <%= @house.longitude %>),
    		          zoom: 14,
    		          mapTypeId: google.maps.MapTypeId.ROADMAP
    		        }
    		        var map = new google.maps.Map(mapCanvas, mapOptions);
    		        var marker = new google.maps.Marker({
    		        	position: new google.maps.LatLng(<%= @house.latitude %>, <%= @house.longitude %>),
    		        	title: "<%= @house.name %>"
    		        });
    		        marker.setMap(map);
    		      }
    		      google.maps.event.addDomListener(window, 'load', initialize);
		    </script>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12">

        </div>
    </div>
</div>

app/views/houses/_house_details.html.erb
<div class="container">
    <h2 class="text-center">House Details</h2>
    <div class="row text-center js--wp-2">
        <div class="col-md-10 col-md-offset-1 house-facts-box">
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <%= image_tag 'bed.png', class: "smaller-icon" %>
                    <p><%= @house.bedroom %> spacious bedrooms</p>
                </div>
                <div class="col-md-4 col-sm-4">
                    <i class="fa fa-bath" aria-hidden="true"></i>
                    <p><%= @house.bathroom %> full bathrooms</p>
                </div>
                <div class="col-md-4 col-sm-4">
                    <%= image_tag 'garage.png', class: "smaller-icon" %>
                    <p><%= @house.garage %> car garage</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row text-center js--wp-2">
        <div class="col-md-10 col-md-offset-1 house-facts-box">
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <i class="fa fa-th" aria-hidden="true"></i>
                    <p><%= @house.sf %> sq ft. of living space. <br> <%= @house.no_ac_sf %> sq ft. of unconditioned area.</p>
                </div>
                <div class="col-md-4 col-sm-4">
                    <%= image_tag 'balcony.png' %>
                    <p>Dual pane windows throughout offering great lighting. Plus balconies.</p>
                </div>
                <div class="col-md-4 col-sm-4">
                    <%= image_tag 'stove.png' %>
                    <p>Granite counter tops, stainless steel gas range, dishwasher.</p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/houses/create.html.erb
<h1>Houses#create</h1>
<p>Find me in app/views/houses/create.html.erb</p>

app/views/houses/edit.html.erb
<%= render 'form' %>

app/views/houses/index.html.erb
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <h2>Manage Houses</h2>
                        <div class="row">
                            <% @houses.each do |house| %>
                                <div class="col-md-3 col-sm-6">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h3><%= house.name %></h3>
                                        </div>
                                        <div class="panel-body preview">
                                            <%= image_tag house.photos[0].image.url()%>
                                        </div>
                                        <div class="panel-footer">
                                            <%= link_to "Update", edit_house_path(house), class: "label label-primary" %>
                                            <%= link_to "View", house_path(house), class: "label label-success" %>
                                            <%= link_to "Delete", "#", class: "label label-danger" %>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/houses/new.html.erb
<%= render 'form' %>

app/views/houses/show.html.erb
<header class="house-hero-img-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <%= render 'carousel' %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <h1><%= @house.name %></h1>
                <p><%= @house.summary %></p>
                <div class="actions text-center">
                    <%= link_to "Message Realtor", "#", class: "hero-btn text-center", :"data-toggle" => "modal", :"data-target" => "#myModal" %>
                </div>
                <%= render 'pages/message_modal' %>
            </div>
        </div>
    </div>
</header>
<section class="house-facts-section">
    <%= render 'house_details' %>
</section>

<script type="text/javascript">
;( function( $ ) {

	$( '.swipebox' ).swipebox();

} )( jQuery );
</script>

app/views/houses/update.html.erb
<h1>Houses#update</h1>
<p>Find me in app/views/houses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Upperkelly | Hayward's Lovely Houses</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render 'shared/navbar' %>
        <%= render 'shared/message' %>
        <%= yield %>
        <%= render 'shared/footer' %>
    </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, url: message_path) do |f| %>
    <div class="form-group">
          <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Name" %>
    </div>
    <div class="form-group">
        <%= f.telephone_field :phone, class: "form-control", placeholder: "Phone number" %>
    </div>
    <div class="form-group">
        <%= f.text_area :content, rows: 5, class: "form-control", placeholder: "Message" %>
    </div>
    <div class="actions text-center">
      <%= f.submit "Send", class: "hero-btn form-btn" %>
    </div>
<% end %>

app/views/messages/new.html.erb
<header class="message-header">
    <div class="container">
        <div class="hero-box">
            <h1>Contact Us</h1>
            <p>Contact us to learn more about our existing and upcoming developments.</p>
        </div>
    </div>
</header>
<section class="message-form-section">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h2>Send a Message</h2>
                <%= form_for(@message, url: message_path ) do |f| %>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="form-group">
                                  <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Name" %>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="form-group">
                                <%= f.telephone_field :phone, class: "form-control", placeholder: "Phone number" %>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= f.text_area :content, rows: 7, class: "form-control", placeholder: "Message" %>
                    </div>
                    <div class="actions">
                      <%= f.submit "Send", class: "hero-btn" %>
                    </div>
                <% end %>
            </div>
            <div class="col-md-6 col-sm-6">
                <h2>Four Bridges at Keller Williams Realty</h2>
                <div class="map">
                </div>
                <p>775 Montery Blvd, San Francisco, CA 94127</p>
            </div>
        </div>
    </div>
</section>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyC01mwpBDbKcqkzn35XJ1kux6gX52w2ORk"></script>

app/views/pages/_front_page.html.erb
<div class="container">
    <% @houses.each_slice(2) do |row| %>
        <div class="row js--wp-1">
            <% row.each do |house| %>
                <div class="col-md-6 col-sm-6 house-box">
                    <div class="panel panel-default">
                        <div class="panel-heading house-img">
                            <%= link_to house_path(house) do %>
                                <%= image_tag house.photos[0].image.url(),class: "img-responsive" %>
                                <% end %>
                            <ul class="house-details text-center">
                                <li><%= house.sf %> sf.</li>
                                <li><%= house.bedroom %> bedrooms</li>
                                <li><%= house.bathroom %> bathrooms</li>
                                <li><%= house.garage %> car gar.</li>
                            </ul>
                        </div>
                        <div class="panel-body">
                            <ul class="house-name-price-view text-center">
                                <li><%= house.name %></li>
                                <li><%= price_conver house.price %></li>
                                <li>
                                    <%= link_to house_path(house) do %>
                                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                                    <% end %>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/pages/_message_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times" aria-hidden="true"></i></button>
                <h3 class="modal-title" id="myModalLabel">Drop a line</h3>
            </div>
            <div class="modal-body">
                <%= render 'messages/form' %>
            </div>
        </div>
    </div>
</div>

app/views/pages/_realtor-section.html.erb
<div class="container">
    <div class="row text-center">
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="row">
                <div class="col-md-4 col-sm-4 realtor-img">
                    <%= image_tag 'realtor.png' %>
                </div>
                <div class="col-md-8 col-sm-8 realtor-details">
                    <h2>Shianne Kurkina</h2>
                    <ul>
                        <li>Realtor, # 01964246</li>
                        <li>415-975-1207</li>
                    </ul>
                    <%= link_to "Contact Me", "#", class: "home-btn hero-btn realtor-btn", :"data-toggle" => "modal", :"data-target" => "#myModal"%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<header>
    <div class="container-outside">
        <div class="row">
            <div class="col-sm-8 col-sm-push-4">
                <%= image_tag "hero2.jpg", class: "img-responsive hero-img" %>
            </div>
            <div class="col-sm-4 col-sm-pull-8">
                <div class="hero-text">
                    <h1>Brand New<br> Homes<br> in Hayward</h1>
                </div>
                <%= link_to "Request a Callback", "#", class: "hero-btn home-btn", :"data-toggle" => "modal", :"data-target" => "#myModal" %>
                <%= render 'message_modal' %>
            </div>
        </div>
    </div>
</header>
<section class="request-calback-section text-center">
    <div class="container">
        <h2>Homes Built For Your Family</h2>
        <%= link_to "Request a Callback", "#", class: "hero-btn", :"data-toggle" => "modal", :"data-target" => "#myModal" %>
    </div>
</section>
<section class="front-page">
    <%= render 'pages/front_page' %>
</section>
<section class="realtor-section">
    <%= render 'pages/realtor-section' %>
</section>
<section class="notice-section">
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1">
            <p>We seek to ensure that all of the data presented on the site regarding new homes and new home communities is current and accurate. However, we do not assume any liability for inaccuracies. It is your responsibility to independently verify the information on the site.</p>
        </div>
    </div>
</section>

app/views/photos/_list.html.erb
<% if @photos %>
    <div class="row">
        <% @photos.each do |photo| %>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading preview">
                        <%= image_tag photo.image.url() %>
                    </div>
                    <div class="panel-body">
                        <span class="pull-right">
                            <%= link_to photo, remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
        					    <i class="fa fa-times fa-lg"></i>
        					<% end %>
                        </span>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/photos/destroy.js.erb
$('.photos-render').html("<%= j render 'photos/list' %>")

app/views/shared/_devisemessage.html.erb
<% if resource.errors.any? %>
    <script>
        <% resource.errors.full_messages.each do |msg| %>
            toastr.error('<%= msg %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="container">
        <div class="row text-center">
            <div class="col-md-3 col-sm-3">
                <figure class="logo-footer">
                    <%= image_tag 'logo-white.png' %>
                </figure>
            </div>
            <div class="col-md-6 col-sm-6">
                <p>Copyright &copy;  2010-2017 Four Bridges at Keller Williams Realty. All rights reserved</p>
            </div>
            <div class="col-md-3 col-sm-3">
                <ul>
                    <li><%= link_to "Contact", message_path %></li>
                    <li><%= link_to "Calculator",'https://www.zillow.com/mortgage-calculator/' %></li>
                </ul>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 ali-details">
                <p>
                    Made with <i class="fa fa-heart" aria-hidden="true"></i> by Ali Ramazon <br>
                    safarnov@gmail.com
                </p>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |f| %>
            <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
            toastr['<%= type %>']('<%= f[1] %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="top-nav">
    <div class="container navigation">
        <div class="logo">
            <%= link_to image_tag("logo1.png"), root_path, class: 'pull-left' %>
            <%= link_to image_tag("logo-white.png"), root_path, class: 'pull-left logo-sticky' %>
        </div>
         <a class="mobile-nav-icon js--nav-icon"><i class="fa fa-list" aria-hidden="true"></i></a>
        <ul class="top-nav-links pull-right js--top-nav-links">
            <% if admin_signed_in? %>
                <li><%= link_to "Create House", new_house_path %></li>
                <li><%= link_to "Manage Houses", houses_path %></li>
                <li><%= link_to "Admin Account", edit_admin_registration_path %></li>
                <li><%= link_to "Sign Out",destroy_admin_session_path, method: :delete %></li>
            <% else %>
                <% @houses.each do |house| %>
                    <li><%= link_to house.name, house_path(house) %></li>
                <% end %>
            <% end %>
        </ul>
    </div>
</nav>

<script src="https://cdn.rawgit.com/vast-engineering/jquery-popup-overlay/1.7.13/jquery.popupoverlay.js"></script>